### ISSUE TITLE
Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null

### ISSUE THREAD

**Issue by igor-godin** [confluentinc/confluent-sigma#30]
Hello!
Most of Sigma rules written for SysMon Events. And most of them has "category" field in "logsource" section. Category field contain one of sysmon event type - process_creation, image_load or another.  When we load rules to Kafka topic we see "Adding sigma rule" messages with "logsource":{"product":"windows","service":null} section. So it seams, that loader ignore "category" field in rule and expect "service" filed, which is absent. So when we start  confluent-sigma we get an error:

 INFO | 2023-06-26 10:55:54,277 | ShutdownableThread.java | 59 | Starting
 INFO | 2023-06-26 10:55:54,289 | SigmaRulesFactory.java | 213 | checking product: windows service: null
 INFO | 2023-06-26 10:55:54,289 | SigmaRulesFactory.java | 214 | sigma rule product: windows service: null
 INFO | 2023-06-26 10:55:54,290 | SigmaRulesFactory.java | 213 | checking product: windows service: security
 INFO | 2023-06-26 10:55:54,291 | SigmaRulesFactory.java | 214 | sigma rule product: windows service: security
 INFO | 2023-06-26 10:55:54,292 | SigmaRulesFactory.java | 213 | checking product: windows service: security
 INFO | 2023-06-26 10:55:54,292 | SigmaRulesFactory.java | 214 | sigma rule product: windows service: security
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null

**Comment by wlaforest** [comment]
Would it be possible for you to attach the sample sigma rule and an example matching record.  I can fix this regardless but it helps us with our testing (unit, regression, etc).

**Comment by wlaforest** [comment]
Igor,

How are you executing the loader and what version are you using?  This sounds like a bug we fixed a while back with an old version.

**Comment by igor-godin** [comment]
O, yes I use release version 1.2.1, while current is 1.3.2. Will it run with Confluent Community Edition which has no ui?

**Comment by wlaforest** [comment]
It works just fine with Community edition.  So 1.2.2 is the last official release we have.  We are currently working on 1.3.0 that I'm hoping to have out in the next month.   I would suggest you run off of main while you are testing but if you get to a point where you are ready to move this into production I would ensure there is a release for you.

**Comment by wlaforest** [comment]
I'm going to close this ticket but as mentioned if you want to send some rules you want to use and some exemplar records I will add it into our test cases.
